#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin

main(_) ->
    ok = application:start(pubsubpoll),
    {ok, _ChanA} = pubsubpoll:create_channel(chan_a, {name, "Robert"}),
    {ok, _ChanB} = pubsubpoll:create_channel(chan_b, {}),
    io:format("Chan: ~p~n", [pubsubpoll:channels()]),
    {ok, ClientPid} = pubsubpoll:create_client(),
    io:format("Client: ~p~n", [ClientPid]),
    pubsubpoll:suscribe(ClientPid, chan_a),
    flood(10000).

flood(0) ->
    ok;
flood(Cpt) ->
    ok = pubsubpoll:publish([{name, "Robert"}, {flavor, "Strawberry"}]),
    flood(Cpt -1).