#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin

main(_) ->
    ok = application:start(pubsubpoll),
    {ok, _ChanA} = pubsubpoll:create_channel(chan_a, {name, "Robert"}),
    {ok, _ChanB} = pubsubpoll:create_channel(chan_b, {}),
    io:format("Chan: ~p~n", [pubsubpoll:channels()]),
    ok = pubsubpoll:publish([{name, "Robert"}]),
    io:format("Filter ~w~n", [psp_channel:filter(chan_a)]).
